name: Build Debian Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Sets up makedeb using the official GitHub Action
      - name: Set up makedeb
        uses: makedeb/setup-makedeb@v1

      # 3. Builds the package using makedeb
      - name: Build Package
        run: makedeb -s --no-confirm

      # 4. Uploads the final .deb file as a build artifact
      - name: Upload .deb Package
        uses: actions/upload-artifact@v4
        with:
          name: i3ipc-glib-deb
          path: "*.deb"
