name: Build i3ipc-glib on Debian

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            devscripts \
            debhelper \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libxcb1-dev \
            xcb-proto \
            libglib2.0-dev \
            libjson-glib-dev \
            gtk-doc-tools \
            gobject-introspection

      - name: Run autogen.sh
        run: ./autogen.sh --prefix=/usr

      - name: Build the deb package
        run: debuild -us -uc

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: i3ipc-glib-deb
          path: ../*.deb
