name: Build i3ipc-glib DEB Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up makedeb environment
      - name: Install makedeb
        run: |
          wget -O makedeb.deb https://github.com/makedeb/makedeb/releases/latest/download/makedeb.deb
          sudo dpkg -i makedeb.deb
          sudo apt-get update
          sudo apt-get install -y makedeb

      # Install dependencies for building i3ipc-glib
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libxcb1-dev \
            xcb-proto \
            libglib2.0-dev \
            libjson-glib-dev \
            gtk-doc-tools \
            gobject-introspection

      # Build the project
      - name: Build i3ipc-glib
        run: |
          ./autogen.sh --prefix=/usr
          make
          sudo make install

      # Create DEB package using makedeb
      - name: Create DEB package
        run: |
          makedeb -s --no-confirm
          mv *.deb i3ipc-glib.deb

      # Upload the DEB package as an artifact
      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: i3ipc-glib-deb
          path: i3ipc-glib.deb
